backend:
  name: github
  repo: micho9879/polski-cms
  branch: main
  use_pkce: true
  app_id: Ov23li0ZsiUrwCSnuMxQ

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "notatki"
    label: "Notatki dla uczniów"
    folder: "public/data/notatki"
    create: true
    extension: "json"
    format: "json"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Miniaturka", name: "thumbnail", widget: "image", required: false }
      - { label: "Treść", name: "content", widget: "markdown" }
